services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  gin:
    build:
      context: ./gin
    volumes:
        - ./gin:/myapp 
    ports:
      - "8080:8000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql_data:
